GET http://localhost:8090/api/posts

###

GET http://localhost:8090/api/post/1

###

POST http://localhost:8090/api/writePost
Content-Type: application/json

{
  "title": "ILoveYouMartin",
  "content": "SoMuch"
}

###
POST http://localhost:8090/api/updatePost
Content-Type: application/json

{
  "title": "ILoveYouMartin",
  "content": "SoMuch"
}

###
GET http://localhost:8090/api/deletePost/1

